[package]
name = "lambda_s3_migrate"
version = "0.1.0"
edition = "2021"

[dependencies]
rusoto_core = "0.47"
rusoto_s3 = "0.47"
log = "0.4"
simple_logger = "1.0"
tokio = { version = "1", features = ["full"] }
image = "0.24"
futures-util = "0.3"
bytes = "1"
